### ISSUE TITLE
No "Clear Solution IntelliSense Cache" button

### ISSUE THREAD

**Issue by Mr-Auto** [PeterMacej/clear-intellisense-cache#2]
Does this extension only work with project that use they .sln file?
I'm using CMake only

Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.10.3

**Comment by PeterMacej** [comment]
I suspect that a .sln file is required. Otherwise, the .suo file inside the .vs folder with the IntelliSense cache is not created. I wasn't even aware that VS can work without sln files.

**Comment by Mr-Auto** [comment]
I was sure i have the .vs folder in my project, but now i see that's not the case. Thou I'm sure i had issues with intellisense remembering some stupid code error when i removed that part of the code.

Guess i close this for now
